name: Player One To Start
favicon: null
layout_spectrum: 0.9538
typography_spectrum: 0.7685352333355695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#706d68'
    - '#b79989'
    - '#57413f'
    - '#e5d1b9'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.35340239363722503
  rhythmicContrast: 0.75
purpose: []
